spring:
  application:
    name: order

datasource:
          url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
          username: hsx
          password: 123456
env:
  dev
